'use client'

import { useState } from 'react'
import { ChevronDown, ExternalLink, FileText, Image as ImageIcon, Mail, Menu, Plus, Sparkles, X } from 'lucide-react'

const sections = [
  { id: 'research', label: 'Research & Publications', eyebrow: '01', color: 'sage', intro: 'Turning complex questions into useful, evidence-based work.', items: [
    { title: 'NanoVLM', meta: 'Published · 2026', text: 'A vision-language model for electron microscopy characterization, validated on 12,847 annotated images with 90.2% defect classification accuracy.', proof: 'Journal article · DOI 10.1166/jno.2026.3879' },
    { title: 'Sustainable Olympic Events', meta: 'Published · 2025', text: 'Built a hybrid AHP, EWM, and Natural Breaks model across 132 years of Olympic history, 47 events, and 987 samples.', proof: 'Conference paper · DOI 10.62051/pdfee298' },
    { title: 'Computerpreter', meta: 'Copyright registered · 2026', text: 'A multimodal ASL translation system using Random Forests, LSTMs, temporal convolutional networks, and Transformers.', proof: 'U.S. Copyright TXu 2-561-060' },
  ]},
  { id: 'service', label: 'Community & Leadership', eyebrow: '02', color: 'peach', intro: 'Making technical learning and communication more accessible.', items: [
    { title: 'Salt Lake AI & App Collective', meta: 'Co-Founder & President', text: 'Built a nationwide student AI education community, organized a 130+ participant workshop, and co-judged a student AI championship.', proof: 'Programs · workshops · mentorship' },
    { title: 'Frontlines Summer Policy Fellowship', meta: 'Salt Lake City Chapter Director', text: 'Led outreach and fellow training while authoring a policy brief on AI and rural healthcare equity.', proof: 'Policy brief · chapter materials' },
    { title: 'STEM access through ASL', meta: 'Community education', text: 'Produced four ASL-interpreted STEM laboratory videos and partnered with Sorenson to expand real-world testing.', proof: 'Video reel · partnership notes' },
  ]},
  { id: 'stem', label: 'STEM Achievements', eyebrow: '03', color: 'blue', intro: 'Competing, building, and learning across computer science, math, biology, chemistry, and physics.', items: [
    { title: 'AI & Computing', meta: 'National and international', text: 'USAAIO National Bronze Medal; USACO Platinum; Presidential AI Challenge Utah and West Region Champion; CAC National 2nd Place.', proof: 'Awards · project demos' },
    { title: 'iGEM 2025', meta: 'Student Team Leader', text: 'Led human practices, community outreach, commercialization, and final defenses in Paris. Global First Runner-up and Gold Medal.', proof: 'Team wiki · project presentation' },
    { title: 'Mathematics & Sciences', meta: 'Olympiads and fairs', text: 'USAMO/USAJMO finalist, AIME qualifier, Physics Bowl Global Tied 1st, USNCO National High Honors, and USEF placements.', proof: 'Certificates · competition results' },
  ]},
  { id: 'music', label: 'Music & Humanities', eyebrow: '04', color: 'lilac', intro: 'A creative practice that keeps my work human, expressive, and connected.', items: [
    { title: 'Piano', meta: 'National 1st place · MTNA 2025', text: 'Utah 1st place, Southwest Region 1st place, and National 1st place in piano duet; WPTA International Gold Award.', proof: 'Performance recordings · awards' },
    { title: 'Languages & culture', meta: 'Chinese and ASL', text: 'Chinese-language speech honors, ASL Literature Competition 1st place, and Utah ASL State Competition wins.', proof: 'Certificates · performance photos' },
  ]},
]

function ProofShelf() {
  const [files, setFiles] = useState<string[]>([])
  function addFiles(list: FileList | null) { if (!list) return; setFiles(prev => [...prev, ...Array.from(list).map(file => file.name)]) }
  return <section className="proof" id="proof"><div className="section-heading"><div><p className="eyebrow">Proof shelf</p><h2>Keep the evidence close.</h2></div><p className="section-note">A simple place for PDFs, images, recordings, and links that substantiate each story.</p></div><div className="upload-grid"><label className="upload-card"><input type="file" accept=".pdf,.doc,.docx" multiple onChange={e => addFiles(e.target.files)} /><FileText /><strong>Upload documents</strong><span>PDFs, certificates, papers</span><small><Plus /> Add files</small></label><label className="upload-card"><input type="file" accept="image/*,video/*,audio/*" multiple onChange={e => addFiles(e.target.files)} /><ImageIcon /><strong>Upload media</strong><span>Photos, demos, recordings</span><small><Plus /> Add media</small></label><div className="upload-card link-card"><ExternalLink /><strong>Add a link</strong><span>DOIs, project sites, videos</span><button type="button">Paste link</button></div></div>{files.length > 0 && <div className="file-list"><span>Added this session</span>{files.map((file, i) => <div key={`${file}-${i}`}><FileText /> {file}</div>)}</div>}<p className="edit-hint"><Sparkles /> This shelf is designed as a reusable template. Connect it to your preferred storage when you are ready to publish private evidence.</p></section>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [open, setOpen] = useState<string | null>('research')
  return <main><header className="topbar"><a className="brand" href="#top"><span>FY</span><div><strong>Forest Young</strong><small>Portfolio · 2026</small></div></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button><nav className={menuOpen ? 'open' : ''}>{sections.map(section => <a key={section.id} href={`#${section.id}`} onClick={() => setMenuOpen(false)}>{section.label}</a>)}<a href="#proof">Proof shelf</a></nav><a className="contact" href="mailto:annyniu1970@gmail.com"><Mail /> Say hello</a></header><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Student · Researcher · Builder · Musician</p><h1>Curiosity, made <em>useful.</em></h1><p className="lede">I am Forest Young — a high school student exploring the space where artificial intelligence, science, accessibility, and creative expression meet.</p><div className="hero-actions"><a className="primary" href="#research">Explore my work <ChevronDown /></a><a className="text-link" href="#proof">View proof shelf <ExternalLink /></a></div></div><div className="hero-card"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="initials">FY</div><p>Skyline High School</p><div className="stats"><span><b>4.0</b> GPA</span><span><b>36</b> ACT</span><span><b>20</b> AP exams</span></div></div></section><section className="overview"><div><p className="eyebrow">At a glance</p><h2>A portfolio that reads like a map.</h2></div><div className="overview-grid">{sections.map(section => <a key={section.id} href={`#${section.id}`} className={`overview-card ${section.color}`}><span>{section.eyebrow}</span><strong>{section.label}</strong><small>{section.items.length} stories to explore <ExternalLink /></small></a>)}</div></section><div className="content">{sections.map(section => <section className="category" id={section.id} key={section.id}><button className="category-head" onClick={() => setOpen(open === section.id ? null : section.id)} aria-expanded={open === section.id}><span className={`number ${section.color}`}>{section.eyebrow}</span><span><strong>{section.label}</strong><small>{section.intro}</small></span><ChevronDown className={open === section.id ? 'rotated' : ''} /></button>{open === section.id && <div className="story-grid">{section.items.map(item => <article className="story" key={item.title}><div className="story-meta">{item.meta}</div><h3>{item.title}</h3><p>{item.text}</p><div className="proof-line"><FileText /> {item.proof}</div></article>)}</div>}</section>)}</div><ProofShelf /><footer><span>Forest Young · Salt Lake City, Utah</span><a href="mailto:annyniu1970@gmail.com">annyniu1970@gmail.com</a><span>Built to grow with the story.</span></footer></main>
}
